
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 18 01:33:26 MST 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Interrogacion_Inicial = 31;
  public static final int Interrogacion_Final = 32;
  public static final int Y = 27;
  public static final int If = 10;
  public static final int Parentesis_Inicial = 36;
  public static final int Caracter_Especial = 22;
  public static final int Dos_Puntos = 29;
  public static final int Dato_Entero = 5;
  public static final int Else = 11;
  public static final int Tipo_Dato = 4;
  public static final int Break = 12;
  public static final int Dato_Double = 6;
  public static final int Arroba = 33;
  public static final int Dato_Float = 7;
  public static final int Punto_Y_Coma = 30;
  public static final int Punto = 28;
  public static final int While = 16;
  public static final int Division = 21;
  public static final int Cadena = 9;
  public static final int Exclamacion_Inicial = 23;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Switch = 13;
  public static final int Linea = 2;
  public static final int ERROR = 41;
  public static final int Do = 15;
  public static final int Case = 14;
  public static final int Llave_Inicial = 34;
  public static final int Dato_Char = 8;
  public static final int Identificador = 39;
  public static final int Exclamacion_Final = 24;
  public static final int Resta = 19;
  public static final int Porcentaje = 26;
  public static final int Llave_Final = 35;
  public static final int Multiplicacion = 20;
  public static final int Gato = 25;
  public static final int Numero = 40;
  public static final int Suma = 18;
  public static final int Main = 38;
  public static final int Igual = 17;
  public static final int Parentesis_Final = 37;
  public static final int Comillas = 3;
}

